jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Gradle
      run: './gradlew build

        cp /home/runner/work/forecastie/forecastie/app/build/outputs/apk/release/app-release-unsigned.apk
        /home/runner/work/forecastie/forecastie/forecastie.apk

        pwd > file_list.txt

        ls -lR >> file_list.txt

        '
    - continue-on-error: true
      name: Upload .apk
      uses: actions/upload-artifact@v1
      with:
        name: Forecastie
        path: forecastie.apk
  release:
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GHR_PATH: /github/workspace/forecastie.apk
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      name: Release
      uses: fnkr/github-action-ghr@v1.3
name: Build and release
on:
  repository_dispatch:
    types: trigger-ga___android.yml
